sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.9.0

language: node_js

node_js:
 - stable

git:
 depth: 10

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - devtools/run-tests.sh

notifications:
  irc: 
    channels:
      - "chat.freenode.net#caliopdev"
    use_notice: true
