export { default as ManageEntityTags } from './components/ManageEntityTags';
export { default as TagItem } from './components/TagItem';
export { default as TagFieldGroup } from './components/TagFieldGroup';
export { default as TagsForm } from './components/TagsForm';
export { default as withTags } from './hoc/withTags';
export * from './hooks/useTags';
export * from './services/getTagLabel';
export * from './services/getTagNamesInCommon';
export * from './services/searchTags';
export * as store from './store';
