version: '2'
volumes:
  index:
    driver: local
  db:
    driver: local
  store:
    driver: local
services:
  # Caliopen APIv2
  api:
    image: public-registry.caliopen.org/api:compose
    links:
      - apiv1:apiv1.dev.caliopen.org
      - redis:redis.dev.caliopen.org
      - cassandra:cassandra.dev.caliopen.org
      - nats:nats.dev.caliopen.org
      - elasticsearch:es.dev.caliopen.org
      - object_store:minio.dev.caliopen.org
    expose:
      - "31415"

  # Caliopen APIv1
  apiv1:
    image: public-registry.caliopen.org/apiv1:compose
    links:
      - redis:redis.dev.caliopen.org
      - cassandra:cassandra.dev.caliopen.org
      - elasticsearch:es.dev.caliopen.org
    expose:
      - "6543"

  # ### Redis Database
  #
  # Used to store sessions.
  redis:
    image: redis
    expose:
      - "6379"

  # ### Cassandra
  #
  # Cassandra is used as the reference storage for business data
  cassandra:
    image: scylladb/scylla
    expose:
      - "9042"
      - "9160"
      - "7000"
    volumes:
      - db:/var/lib/scylla
    entrypoint:
      - /docker-entrypoint.py
      - --memory
      - 512M

  # ### Elasticsearch
  #
  # Used to index mail content and ensure great research performances.
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    expose:
      - "9200"
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
    volumes:
      - index:/usr/share/elasticsearch/data

  # Caliopen cli tool
  cli:
    image: public-registry.caliopen.org/cli:compose
    links:
      - cassandra:cassandra.dev.caliopen.org
      - elasticsearch:es.dev.caliopen.org
      - broker:broker.dev.caliopen.org
    environment:
      CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    volumes:
      - .:/srv/caliopen/src/backend/devtools

  # Caliopen frontend
  frontend:
    image: public-registry.caliopen.org/frontend:compose
    links:
      - api:api.dev.caliopen.org
    ports:
      - "127.0.0.1:4000:4000"
  # Broker
  broker:
    image: public-registry.caliopen.org/broker:compose
    links:
      - cassandra:cassandra.dev.caliopen.org
      - elasticsearch:es.dev.caliopen.org
      - object_store:minio.dev.caliopen.org
      - nats:nats.dev.caliopen.org
      - message_handler:mc.dev.caliopen.org
    ports:
      - "127.0.0.1:2525:2525"
  # NATS
  nats:
    image: nats:0.9.6
    expose:
      - "4222"

  # NATS Message Handler
  message_handler:
    image: public-registry.caliopen.org/message_handler:compose
    links:
      - cassandra:cassandra.dev.caliopen.org
      - elasticsearch:es.dev.caliopen.org
      - nats:nats.dev.caliopen.org

  # object storage
  object_store:
    image: minio/minio
    expose:
      - "9090"
    volumes:
      - ../src/backend/configs:/configs
      - store:/export
    command:
      server --address :9090 -C /configs/minio /export

  # Worker for remote identities
  identity_worker:
    image: public-registry.caliopen.org/identity_worker:compose
    links:
      - cassandra:cassandra.dev.caliopen.org
      - object_store:minio.dev.caliopen.org
      - elasticsearch:es.dev.caliopen.org
      - nats:nats.dev.caliopen.org

  # Poller for remote identities
  identity_poller:
    image: public-registry.caliopen.org/identity_poller:compose
    links:
      - identity_worker:identityworker.dev.caliopen.org
      - cassandra:cassandra.dev.caliopen.org
      - nats:nats.dev.caliopen.org

  # Postfix : a complete smpt server that act as the Caliopen's MTA
  # TODO
